#!/bin/bash

set -e

printf "Environment variables:\\n"
printf "SOURCE_BRANCH=\"${SOURCE_BRANCH}\"\\n"
printf "SOURCE_COMMIT=\"${SOURCE_COMMIT}\"\\n"
printf "COMMIT_MSG=\"${COMMIT_MSG}\"\\n"
printf "DOCKER_REPO=\"${DOCKER_REPO}\"\\n"
printf "DOCKERFILE_PATH=\"${DOCKERFILE_PATH}\"\\n"
printf "CACHE_TAG=\"${CACHE_TAG}\"\\n"
printf "IMAGE_NAME=\"${IMAGE_NAME}\"\\n"

# INTERNAL_TAG is only used for extracting the BASE_IMAGE and the VERSION, adding our own tags happens in post_push
INTERNAL_TAG="${SOURCE_BRANCH}"
if test "${SOURCE_BRANCH}" = "master"; then
    INTERNAL_TAG_BASE_IMAGE_PART=$(sed -n "s/ARG BASE_IMAGE=\"\(.*\)\"/\1/p" Dockerfile | sed -e '1 s/:/-/; t')
    INTERNAL_TAG_VERSION_PART=$(sed -n "s/ARG VERSION=\"\(.*\)\"/\1/p" Dockerfile)
    INTERNAL_TAG="${INTERNAL_TAG_VERSION_PART}-on-${INTERNAL_TAG_BASE_IMAGE_PART}"
fi
BASE_IMAGE=$(echo ${INTERNAL_TAG} | awk -F "-on-" '{print $2}' | sed -e '1 s/\-/:/; t')
VERSION=$(echo ${INTERNAL_TAG} | awk -F "-on-" '{print $1}')

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(git rev-parse HEAD)

printf "Build variables:\\n"
printf "BASE_IMAGE=\"${BASE_IMAGE}\"\\n"
printf "VERSION=\"${VERSION}\"\\n"
printf "INTERNAL_TAG=\"${INTERNAL_TAG}\"\\n"
printf "BUILD_DATE=\"${BUILD_DATE}\"\\n"
printf "VCS_REF=\"${VCS_REF}\"\\n"
printf "DOCKERFILE_PATH=\"${DOCKERFILE_PATH}\"\\n"
printf "IMAGE_NAME=\"${IMAGE_NAME}\"\\n"

docker build \
    --build-arg BASE_IMAGE=${BASE_IMAGE} \
    --build-arg VERSION=${VERSION} \
    --build-arg INTERNAL_TAG=${INTERNAL_TAG} \
    --build-arg BUILD_DATE=${BUILD_DATE} \
    --build-arg VCS_REF=${VCS_REF} \
    --file ${DOCKERFILE_PATH} \
    --tag ${IMAGE_NAME} \
    .
